### CRIAR USUÁRIO
POST http://localhost:8081/usuarios
Content-Type: application/json

{
  "nome": "User1",
  "cpf": "70703407429",
  "time": "RH"
}

###

### PESQUISAR USUÁRIO POR ID
GET http://localhost:8081/usuarios/id/1

###


### PESQUISAR USUÁRIO POR CPF
GET http://localhost:8081/usuarios/cpf/70703407429

###

### LISTAR TODOS OS USUÁRIOS
GET http://localhost:8081/usuarios

###

### LISTAR USUÁRIOS POR TIME
GET http://localhost:8081/usuarios/time/RH
