### ==========================================
### MÓDULO DE USUÁRIOS
### ==========================================

### 1. CRIAR USUÁRIO
# Cria um novo usuário no sistema. 
# Times disponíveis: PAYMENTS, RH, TI
POST http://localhost:8081/usuarios
Content-Type: application/json

{
  "nome": "André",
  "cpf": "08703096489",
  "time": "TI"
}

###

### 2. PESQUISAR USUÁRIO POR ID
GET http://localhost:8081/usuarios/id/1

###

### 3. PESQUISAR USUÁRIO POR CPF
GET http://localhost:8081/usuarios/cpf/70703907429

###

### 4. LISTAR TODOS OS USUÁRIOS
GET http://localhost:8081/usuarios

###

### 5. LISTAR USUÁRIOS POR TIME
# Opções: PAYMENTS, RH, TI
GET http://localhost:8081/usuarios/time/TI

###

### 6. ATUALIZAR TIME DO USUÁRIO
PUT http://localhost:8081/usuarios/1/time
Content-Type: application/json

{
  "time": "RH"
}

###

### ==========================================
### MÓDULO DE CHAMADOS
### ==========================================

### 7. CRIAR CHAMADO
# Tipos: WITHDRAWL, DEPOSIT, MY_ACCOUNT, TECHINAL_ISSUES
# Prioridades: BAIXA, NORMAL, ALTA
# Escopos: TODOS, SOMENTE_EU
POST http://localhost:8081/chamados
Content-Type: application/json

{
  "tipo": "MY_ACCOUNT",
  "prioridade": "BAIXA",
  "usuario": {
    "id": 2
  },
  "titulo": "Erro no sistema de integração",
  "descricao": "O sistema apresenta falha ao sincronizar dados com o banco H2",
  "escopo": "TODOS"
}

###

### 8. LISTAR TODOS OS CHAMADOS
GET http://localhost:8081/chamados

###

### 9. BUSCAR CHAMADO POR ID
GET http://localhost:8081/chamados/id/1

###

### 10. FILTRAR CHAMADOS POR STATUS
# Opções: ABERTO, EM_PROGRESSO, AGUARDANDO_USUARIO, FECHADO
GET http://localhost:8081/chamados/status/ABERTO

###

### 11. FILTRAR CHAMADOS POR TIPO
GET http://localhost:8081/chamados/tipo/TECHINAL_ISSUES

###

### 12. FILTRAR CHAMADOS POR PRIORIDADE
GET http://localhost:8081/chamados/prioridade/ALTA

###

### 13. LISTAR CHAMADOS DE UM USUÁRIO ESPECÍFICO
GET http://localhost:8081/chamados/usuario/1

###

### 14. ATUALIZAR STATUS (FECHAR CHAMADO / INATIVAR)
# Envia o enum como uma String simples no corpo da requisição
PUT http://localhost:8081/chamados/1/status
Content-Type: application/json

"EM_PROGRESSO"

### 15. ADICIONAR COMENTÁRIO
# No 'id' da URL, coloque o ID do chamado (ex: 1)
# No 'autorId', passe o ID do usuário que está comentando
POST http://localhost:8081/chamados/1/comentarios?autorId=2
Content-Type: application/json

"Este é um comentário de teste para validar a atualização da hora."